name: Clear README Periodically

on:
  schedule:
    - cron: '0 0 */14 * *'  # Runs every 14 days at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  clear:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Clear README
        run: |
          echo "# Housing Listings" > README.md
          echo "" >> README.md
          echo "Last cleared: $(date '+%Y-%m-%d')" >> README.md
      
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add README.md
          git commit -m "Clear README contents: $(date '+%Y-%m-%d')"
          git push
